### ISSUE TITLE
[ISSUE] Radio volume not lowering during dialogue

### ISSUE THREAD

**Issue by iCeParadox64** [gta-chaos-mod/Trilogy-ASI-Script#113]
Normally in the game, when characters are talking during a mission, the car radio volume will lower during the dialogue so you can actually hear what's being said. With the Chaos mod installed, the radio volume never lowers, and it's extremely hard to hear dialogue. And if you're curious, this happens regardless of whether **AllowRadioInEveryVehicle** is set to true or false.
I know most everyone using this mod has probably completed the game many times before and doesn't _need_ to hear the dialogue, myself included, but it's still very annoying and I'd love if this were fixed.

**Comment by Lordmau5** [comment]
I'm pretty sure I'll be removing the `AllowRadioInEveryVehicle` in the 3.0 rewrite anyway, so that should be fixed.

If it were to come back it would be in a separate mod that I would suggest people to run alongside Chaos Mod

**Comment by Lordmau5** [comment]
Removed the option in v3.0.1

**Comment by iCeParadox64** [comment]
It's been a long while but I've finally gotten the chance to play the new version, and this issue is very much still present. Like I said in the initial post, the `AllowRadioInEveryVehicle`  setting had nothing to do with the bug, and I can confirm that removing the `TrilogyChaosMod.SA.asi` file still fixes the issue, and it's also not a conflict with another mod. Please reopen this and have another look at it, thank you.
